# TODO: all the composing and async declarations could be done here
exports[name] = require "./Fuell/#{name}" for name in [
  "Action"
  "Actions"
  "Array"
  "Arrays"
  "Environment"
  "Function"
  "FunctionByLengthMap"
  "FunctionByTypesPairs"
  "FunctionTemplate"
  "Keys"
  "Map"
  "Maps"
  "Number"
  "Numbers"
  "Object"
  "Optional"
  "Optionals"
  "Pair"
  "Pairs"
  "RegExp"
  "Set"
  "SortedArray"
  "String"
  "Strings"
  "Text"
]
